### ISSUE TITLE
$state.go on a sibling tab state does not make the target tab as active

### ISSUE THREAD

**Issue by CarbonFactory** [rpocklin/ui-router-tabs#69] opened 2016-03-14 06:51 UTC
Assume we have 3 tabs: `tab1, tab2 & tab3`

If we are in tab1 and execute `$state.go('tab2')`, tab2 is displayed but the `active` class  is not added to the tab2 and instead stays with tab1

This gives an impression that tab1 is active whereas in reality  its not and it should be tab2 that should be active

**Comment by rpocklin** [comment] 2016-03-18 01:07
Sounds like a dupe of https://github.com/rpocklin/ui-router-tabs/issues/70
what version of Bootstrap.UI are you using?

**Comment by CarbonFactory** [comment] 2016-03-19 13:57
1.2.3

**Comment by rpocklin** [comment] 2016-04-05 22:10
Can you send me a plunkr?

**Closed** 2016-04-05 22:24 UTC
