### ISSUE TITLE
Tab contents empty following file-rev/usemin minification

### ISSUE THREAD

**Issue by skidvd** [rpocklin/ui-router-tabs#36] opened 2015-08-31 16:57 UTC
I have an application that is working fine ... until I attempt to file-rev and minimize it.  It makes use of tabs nested within the main view as follows:

detail.html contains
```
<div class="jobDetail" style="width: 100%; overflow: auto;">
    <tabs data="tabData" type="tabs" template-url="detailTabs.html"/>
    <ui-view></ui-view> <!-- ="detailTabs" -->
</div>
```

details.html contains the following:
```
<tabset class="tab-container" type="{{::type}}" vertical="{{::vertical}}" justified="{{::justified}}">
    <tab class="tab" ng-repeat="tab in ::tabs" active="tab.active" disabled="tab.disabled" ng-click="go(tab)">
        <tab-heading>
            {{::tab.heading}}
            <span ng-if="tab.actionCount" class="action">{{tab.actionCount}}</span>
            <span ng-if="tab.warningCount" class="problem">{{tab.warningCount}}</span>
        </tab-heading>
    </tab>
</tabset>
```

This works perfectly and the tabs behave and display the contents associated with the appropriate states when the code has not yet been minimized.

However, once we minimize via grunt file-rev and usemin, the tab contents are no longer displayed with the above configuration.  It appears as if the <ui-view></ui-view> is not located or not replaced for some reason (yet I have verified and confirmed its existence in the minimized html).

To add to the mystery, if I relocate the <ui-view></ui-view> from detail.html and add it as the last line in detailTabs.html, the contents are then displayed - even following grunt usemin!  Surprising at best - I stumbled upon this while trying to isolate the issue  However, this does not following the documentation examples and causes additional problems downstream as it appears to change where the ui-router current state is set and breaks (or would at least require changes to) logic depending upon it.  As such, this does not appear like a solution at all, just an interesting quirk result.

I am using version 1.5.0 at the moment with this app.

Unfortunately, as this is file-rev/minimization specific, I don't believe a plunker will be useful.

Are there known issues related to using angular-ui-router-tabs with grunt file-rev and usemin minimized html/code?  Are there specific changes or workarounds that I should employ to make this combination work as successfully as it does prior to minimization?

TIA!

**Comment by rpocklin** [comment] 2015-08-31 22:20
I'm not aware of any issues around this (never been raised before).  Usemin is pretty old though and the community has switched to ng-annotate.  I use gulp which uses gulp-ng-annotate, perhaps look into 
https://github.com/mzgol/grunt-ng-annotate for grunt.

This directive ticks the boxes for minification since it double-declares modules and the example works with *ng-strict-di*.  I'd say the issue is more around your project.

**Comment by skidvd** [comment] 2015-09-01 13:56
I can understand why you may think that.  However, all other areas of the project that are external to the tabs are working just fine (both before and after file-rev/minimization).  So far, I have tracked down the trouble spots to being those within the tabs, but I'm not really sure how to reduce it further as the tab content is empty, no errors are produced and the Network tab does NOT reflect that the content is even fetched/loaded.

**Comment by skidvd** [comment] 2015-09-02 21:18
FYI, I have built a trivial yoeman generated sample angular app and integrated three trivial tabs into it.  I am seeing exactly the same results there as well - i.e 1) all non-tab content works perfectly both prior to file-rev/minimization and after and 2) tab based content works perfectly before file-rev/minimization and all tabs have empty content but do not produce any errors afterwards

**Comment by rpocklin** [comment] 2015-09-02 22:21
If you can identify the cause of the issue i'm happy to accept a PR.

**Comment by skidvd** [comment] 2015-09-03 01:29
I'm trying to investigate and will be happy to contribute if I can.  However, I'm not as versed on ui-router and ui-router-tabs as you are.  I believe there is a large clue in the fact that relocating the ui-view directive from detail.html and then add it as the last line in detailTabs.html (as described above) makes the tab contents work and display their contents - even following grunt file-rev/usemin.  Can you shed any light on this clue or perhaps where to dig a bit more within ui-router or ui-router-tabs with that clue in mind?

**Comment by skidvd** [comment] 2015-09-07 22:13
I am continuing to dig into this without much luck so far.  I am going to attempt a different path to further isolate where the issue is.  I plan to create a simple app generated via gulp and slush (instead of grunt and yoeman) to include ui-router-tabs content in to see if I can get any further down the filerev/minimization path with that stack or if I run into the same problems as described above.  More to follow as it is available....

**Comment by jits** [comment] 2015-09-13 16:26
I experienced the same issue @skidvd – the `ui-view` not rendering in the concatenated/built output. After some trial and error I found a potential solution, but with no real explanation just yet. My hunch is it's something to do with template compilation to JavaScript. The following worked for me:

```html
<tabs data="cms.tabs" type="tabs"></tabs>
<div ui-view></div>
```

The important detail is the declaration of the `tabs` tag – I needed to explicitly mark the end tag `</tabs>` instead of ending the tag with ` />`.

Note though, I'm not using `usemin`, so this may or may not solve it for you.

**Comment by rpocklin** [comment] 2015-09-13 21:46
Yeah, that is a thing in angular.  Most browers will handle a self closing custom tag ok but its not part of the html spec - theres plenty of closed issues on angular.js about this - here is one reference:

http://stackoverflow.com/questions/18103183/angular-element-directives-not-displaying-when-using-self-closing-tags

Unfortunately there isn't an easy fix unless you know what you are looking for, but as you pointed out minification will fail. Also not specific to this directive.

**Comment by jits** [comment] 2015-09-13 21:56
Good to know, @rpocklin!

**Comment by rpocklin** [comment] 2015-09-13 22:24
@skidvd from looking at your code this may be the issue (thanks for highlighting that @jits) can you add a closing tags to `<tabs>` and re-test?

**Comment by skidvd** [comment] 2015-09-18 18:32
@jits, @rpocklin,

Great catch!  I can confirm that adding closing ```</tabs>``` fixes the issue when minimized.  BTW, I can also confirm that both the grunt version I started with, as well as the gulp based versions I have been working with will display the same 'failure' behavior when minimized if you don't have the closing ```</tabs>```.  Both work, if you do.

Thanks again to both of you for the assistance!

**Closed** 2015-09-18 18:33 UTC
